[package]
name = "podbox-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "podbox"
path = "src/main.rs"

[dependencies]
podbox-probe = { path = "../podbox-probe" }
podbox-image = { path = "../podbox-image" }
serde_json.workspace = true
podbox-extract = { path = "../podbox-extract" }
podbox-complete = { path = "../podbox-complete" }
podbox-enter = { path = "../podbox-enter" }
podbox-supervise = { path = "../podbox-supervise" }
